version: '3'

volumes:
  allure-docker-service:
    driver: local

services:
  allure-docker-service:
    build:
      context: ../allure-docker-service
      dockerfile: docker-custom/Dockerfile.bionic-custom
      args:
        ALLURE_RELEASE: "2.13.6"
    environment:
      DEV_MODE: 0
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 999999
      #URL_PREFIX: "/my-prefix"
      SECURITY_USER: "my_username"
      SECURITY_PASS: "my_password"
      SECURITY_ENABLED: 0
      PORT: 5052
      API_RESPONSE_LESS_VERBOSE: 1
    ports:
      - "5052:5052"
    volumes:
      - /c/Categories/work/elateral/_temp/projects:/app/projects

      # allure-ui:
      # image: "frankescobar/allure-docker-service-ui"
      # environment:
      # ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:${ALLURE_DOCKER_SERVICE_API_PORT}"
      # ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
      # ports:
      # - "7474:5252"
